name: Lint Protobuf definitions

on:
  push:
    branches: [ main ]
  pull_request:

permissions: {}

jobs:
  buf:
    name: Buf lint, format and breaking change detection
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checking out code
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Buf
        uses: bufbuild/buf-action@8c6a16e16f12ba20b6470afa9c2ba9b5ba8c97c3 # v1.5.0
        with:
          setup_only: true

      - name: Lint protobuf definitions
        run: buf lint

      - name: Format protobuf definitions
        run: buf format --diff --exit-code --path cryptobroker

      # Only meaningful once the cryptobroker.v1 layout is on main.
      - name: Breaking change detection
        if: github.event_name == 'pull_request'
        run: buf breaking --against "https://github.com/${GITHUB_REPOSITORY}.git#branch=${BASE_REF}"
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          BASE_REF: ${{ github.base_ref }}
